### ISSUE TITLE
Shared task paper format

### ISSUE THREAD

**Issue by Aadyant12** [fladhak/creative-summ-data#12]
I have prepared the shared task paper using the format I found on this link: https://2021.emnlp.org/call-for-papers/style-and-formatting. I found this link on the site provided by you: https://www.statmt.org/wmt21/index.html
My paper is thus not been prepared on the OverLeaf template (https://www.overleaf.com/latex/templates/acl-rolling-review-template/jxbhdzhmcpdm).
Kindly confirm that I can submit it in this manner.

**Comment by swiseman** [comment]
This is probably fine for now. We may ask you to reformat before the camera-ready submission deadline. We'll let you know.
