### ISSUE TITLE
test set

### ISSUE THREAD

**Issue by ian0105** [fladhak/creative-summ-data#5]
I am participating in the Movie Scriptbase summary shared task. The release date of the test set has passed, but I don't know where to check it. I'd appreciate it if you could tell me.

**Comment by Aadyant12** [comment]
Same issue for BookSum task. Waiting for update

**Comment by Gunhee-Cho** [comment]
I also want to know answer about the issue.

**Comment by bsy99615** [comment]
Me either. The date of the test set release that you announced was 13, but not yet..

**Comment by swiseman** [comment]
Hi all - we're very sorry for the delay. The BookSum and Scriptbase test sets were not ready by July 13th and so **we will be postponing the system output submission deadline** as well as all the deadlines that follow it. We hope to release the test sets at the end of this week or the beginning of next, and we will follow up soon with a more official announcement. We apologize again for the delay and the confusion!

**Comment by swiseman** [comment]
All test inputs have been pushed to the repo.
