### ISSUE TITLE
System output and description submission

### ISSUE THREAD

**Issue by pyRis** [fladhak/creative-summ-data#6]
Hi, May I please ask where and how to do the submission and what should be the output for system description?

**Comment by swiseman** [comment]
We will post an upload link closer to the date on which summary submissions are due (which has been postponed; see #5). Where do you see "system description"? The FAQ does mention `system_id`, which should just be a string indicating your team name (and should be the same for all submitted summaries).

**Comment by pyRis** [comment]
Sorry, the term was "System Summary", not "System Description"

**Comment by swiseman** [comment]
System summary is the summary your model/system predicts for the corresponding input. It should be a string (just like in the training data). Does that answer your question?

**Comment by pyRis** [comment]
Yes, thank you.
