### ISSUE TITLE
Summary already provided in test set

### ISSUE THREAD

**Issue by Aadyant12** [fladhak/creative-summ-data#7]
I am taking part in the BookSum task. The test set provided also has the summaries. Why is that the case? It is not in the format provided in the Creative-Summ FAQ google doc

**Comment by Aadyant12** [comment]
Also, '2554-chapters' and '4300-chapters' are not present in the 'all_chapterized_books' folder

**Comment by jigsaw2212** [comment]
@Aadyant12 thanks for bringing this to our notice. Adding the summary urls was an error on my part. I've updated the repo.
As for '2554-chapters' and '4300-chapters', I can see both these directories present in the zip file provided here -  https://storage.cloud.google.com/creative-summ-booksum/all_chapterized_books.zip

**Comment by Aadyant12** [comment]
No ‘instance_id’ is present. I believe it's a key thing. Please fix this. I'd request you to kindly postpone the deadline by a day on account of this.
